//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wealth_Management_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class brokerOperation
    {
        public int id { get; set; }
        public string transactionID { get; set; }
        public string trader { get; set; }
        public string shares { get; set; }
        public string item { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> brokerID { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
        public Nullable<int> clientID { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual broker broker { get; set; }
        public virtual investor investor { get; set; }
    }
}
