//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wealth_Management_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class broker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public broker()
        {
            this.investors = new HashSet<investor>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<decimal> commission { get; set; }
        public Nullable<System.DateTime> hireDate { get; set; }
        public Nullable<int> managerID { get; set; }
    
        public virtual management management { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<investor> investors { get; set; }
    }
}
