//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wealth_Management_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dividends_2022
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public Nullable<decimal> january { get; set; }
        public Nullable<decimal> february { get; set; }
        public Nullable<decimal> march { get; set; }
        public Nullable<decimal> april { get; set; }
        public Nullable<decimal> may { get; set; }
        public Nullable<decimal> june { get; set; }
        public Nullable<decimal> july { get; set; }
        public Nullable<decimal> august { get; set; }
        public Nullable<decimal> september { get; set; }
        public Nullable<decimal> october { get; set; }
        public Nullable<decimal> november { get; set; }
        public Nullable<decimal> december { get; set; }
    }
}
