//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wealth_Management_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class investor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public investor()
        {
            this.brokerOperations = new HashSet<brokerOperation>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> memberSince { get; set; }
        public Nullable<decimal> capital { get; set; }
        public Nullable<decimal> latestDividend { get; set; }
        public Nullable<int> brokerID { get; set; }
        public Nullable<int> loginAttempts { get; set; }
        public Nullable<int> isLocked { get; set; }
        public Nullable<System.DateTime> lockOutTime { get; set; }
    
        public virtual broker broker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<brokerOperation> brokerOperations { get; set; }
    }
}
